backend:
  name: git-gateway
  repo: Grandelfino/Blog
  branch: master
  create: 'Create {{collection}} “{{slug}}”'
  update: 'Update {{collection}} “{{slug}}”'
  delete: 'Delete {{collection}} “{{slug}}”'
  uploadMedia: '[skip ci] Upload “{{path}}”'
  deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
locale: ja
media_folder: 'static/media/'
public_folder: '/public'

collections:
  - name: Blog
    label: blog
    label_singular: Blog
    folder: 'content/post'
    path: '{{year}}/{{month}}/{{day}}/index'
    preview_path: post/{{year}}/{{month}}/{{day}}
    media_folder: ''
    public_folder: ''
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish this page on", name: "date", widget: "datetime"}
      # - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Tags(未分類, お知らせ, スポンサーシップ, パワートレイン, シャシ・フレーム, エアロ, 講習会, 走行会, 大会, 新入メンバー)"
        name: "tags"
        required: false
        widget: "list"
      - label: "サムネイル"
        name: "image"
        widget: object
        fields:
          - label: "`featured.jpg`または`featured.png`という名前にすること!"
            name: "filename"
            widget: "image"
            required: false
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          # - {label: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight., name: focal_point, widget: string, required: false, default: "Smart"}